version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - run: scons --version

  hello:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - run: echo "Hello!"

workflows:
  version: 2
  build:
    jobs:
      - build:
          requires:
            - hello
