version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - run: pwd
      - run: ls -la
      - run: sudo apt-get update
      - run: sudo apt-get install scons
      - run: scons --version

  hello:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - run: echo "Hello!"
      - run: cat /etc/issue

workflows:
  version: 2
  build:
    jobs:
      - hello
      - build:
          requires:
            - hello
