version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install scons
      - run: scons --version

workflows:
  version: 2
  build:
    jobs:
      - build
